#+TITLE: Homework 1
#+DATE: January 15, 2019
#+OPTIONS: TOC:nil AUTHOR:nil
#+LATEX: \setcounter{secnumdepth}{-1}
* 1
  Two cases:
** Let $\max(f(n),g(n)) = f(n)$
   Then $f(n)$ is asymptotically greater than $g(n)$.
   Note that
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim\limits_{n\to\infty} \frac{f(n)+g(n)}{f(n)} = \lim\limits_{n\to\infty} \frac{f(n)}{f(n)} + \frac{g(n)}{f(n)} = 1 + 0 = 1
   \end{equation*}
   #+END_EXPORT

   so $f(n)+g(n) = \Theta(f(n)) = \Theta(\max(f(n),g(n)))$. $\qed$
** Let $\max(f(n),g(n)) = g(n)$
   Then $g(n)$ is asymptotically greater than $f(n)$
   Again note that
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim\limits_{n\to\infty} \frac{f(n)+g(n)}{g(n)} = \lim\limits_{n\to\infty} \frac{f(n)}{g(n)} + \frac{g(n)}{g(n)} = 0 + 1 = 1
   \end{equation*}
   #+END_EXPORT

   So $f(n)+g(n) = \Theta(g(n)) = \Theta(\max(f(n),g(n))). \qed$
* 2
  If $f(n) = \Theta(g(n))$, then $f(n) = O(g(n))$ and $f(n) = \Omega(g(n))$.
  That is $\exists c_1,c_2, n_0$ such that $\forall n>n_0, 0 \leq c_1g(n) \leq f(n) \leq c_2g(n)$.
  Squaring this, we get $0 \leq c_1^2g(n)^2 \leq f(n)^2 \leq c_2^2g(n)^2$.
  Therefore, by definition of $\Theta$, $f(n)^2 = \Theta(g(n)^2)$. $\qed$

* 3
  Let $f(n) = n, g(n) = 2n$, then clearly, $f(n) = \Theta(g(n))$,
  however, $2^{f(n)} = 2^n, 2^{g(n)} = 2^{2n}$ and since $n \neq 2n$,
  $2^{f(n)} \neq \Theta(2^{g(n)}). \qed$
* 4
  If $f(n)=\Theta(g(n))$, then $\exists c_1,c_2,n_0 > 0$ such that
  $\forall n\geq n_0$
  #+BEGIN_EXPORT latex
  \begin{align*}
    c_1g(n)\leq &f(n)\leq c_2g(n) \\
    \ln c_1g(n)\leq &\ln f(n)\leq \ln c_2(g(n)) \\
    \ln c_1 + \ln g(n) \leq &\ln f(n) \leq \ln c_2 + \ln g(n)
  \end{align*}
  #+END_EXPORT
  Since we are only interested in asymptotic analysis, the constant terms can be ignored,
  and therefore this show that $\ln(f(n)) = \Theta(\ln(g(n))). \qed$
* 5
  #+BEGIN_EXPORT latex
  \begin{proof}
    Given that $f(n)\ln f(n) = \Theta(n)$,
    then
    \begin{equation*}
      \ln(f(n)\ln f(n)) = \ln f(n) + \ln\ln f(n) =  \Theta(\ln n)
    \end{equation*}
    by problem (4).
    Now notice that $\ln\ln f(n) = O(\ln f(n))$ and so since it has a lower asyptotic
    growth rate it can be ignored for the puprose of asymptotic analysis.
    This means that the above equation can be simplified to $\ln f(n) = \Theta(\ln n)$.
    Now since $\ln f(n)$ and $\ln n$ have the same asymptotic growth rate,
    we can substitute $\ln n$ for $\ln f(n)$ in the original equation:
    \begin{equation*}
      f(n)\ln f(n) = f(n)\ln n = \Theta(n)
    \end{equation*}
    This means that $\exists c_1,c_2,n_0>0$ such that $\forall n>n_0$:
    \begin{align*}
      &c_1n \leq f(n)\ln n \leq c_2n \\
      &c_1\frac{n}{\ln n} \leq f(n) \leq c_2\frac{n}{\ln n}
    \end{align*}
    Which shows that $f(n) = \Theta(\frac{n}{\ln n}). \qedhere$
  \end{proof}
  #+END_EXPORT
* 6
** $1, n^{1/\lg n}$
    Note:
    #+BEGIN_EXPORT latex
    \begin{equation*}
      n^{1/\ln n} =e^\ln{n^{1/\ln n}} = e^{\ln n \frac{1}{\ln n}} = e
    \end{equation*}
    #+END_EXPORT
    and $1 = \Theta(e)$.
** $\ln\ln n$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{\ln\ln n}{1} = \infty
   \end{equation*}
   #+END_EXPORT
** $\sqrt{\ln n}$
   #+BEGIN_EXPORT latex
   \begin{align*}
     \lim_{n\to\infty}\frac{\sqrt{\ln n}}{\ln\ln n} &= \lim_{n\to\infty}\frac{\frac{1}{2n\sqrt{\ln n}}}{\frac{1}{n\ln n}} \\
     &= \lim_{n\to\infty}\frac{n\ln n}{2n\sqrt{\ln n}} \\
     &= \lim_{n\to\infty}\frac{\ln n}{2(\ln n)^{1/2}} \\
     &= \frac{1}{2}\lim_{n\to\infty}(\ln n)^{1/2} \\
     &= \infty
   \end{align*}
   #+END_EXPORT
** $\ln n$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{\ln n}{(\ln n)^{1/2}} = \lim_{n\to\infty}(\ln n)^{1/2} = \infty
   \end{equation*}
   #+END_EXPORT
** $(\ln n)^2$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{(\ln n)^2}{\ln n} = \lim_{n\to\infty}\ln n = \infty
   \end{equation*}
   #+END_EXPORT
** $\sqrt{2n}$
   #+BEGIN_EXPORT latex
   \begin{align*}
     \lim_{n\to\infty}\frac{\sqrt{2n}}{(\ln n)^2} &= \sqrt{2}\lim_{n\to\infty}\frac{\sqrt{n}}{(\ln n)^2} \\
     &= \sqrt{2}\lim_{n\to\infty}\frac{1/\sqrt{n}}{2\ln n/ n} \\
     &= \frac{\sqrt{2}}{2}\lim_{n\to\infty}\frac{\sqrt{n}}{\ln n} \\
     &= \frac{\sqrt{2}}{2}\lim_{n\to\infty}\frac{n}{\sqrt{n}} \\
     &= \infty
   \end{align*}
   #+END_EXPORT
** $n$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{n}{\sqrt{2n}} = \frac{1}{\sqrt{2}}\lim_{n\to\infty}\sqrt{n} = \infty
   \end{equation*}
   #+END_EXPORT
** $n\ln n, \ln(n!)$
   #+BEGIN_EXPORT latex
   \begin{align*}
     \lim_{n\to\infty}\frac{n\ln n}{n} = \lim_{n\to\infty}\ln n = \infty
   \end{align*}
   #+END_EXPORT
   $\ln(n!) = \Theta(n\ln n)$ by corollary (3) common functions handout.
** $n^2$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{n^2}{n\ln n} = \lim_{n\to\infty}\frac{n}{\ln n} = \lim_{n\to\infty}\frac{1}{1/n} = \lim_{n\to\infty} n = \infty
   \end{equation*}
   #+END_EXPORT
** $n^3$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{n^3}{n^2} = \lim_{n\to\infty} n = \infty
   \end{equation*}
   #+END_EXPORT
** $n^{\ln\ln n}$
   #+BEGIN_EXPORT latex
   \begin{align*}
     \lim_{n\to\infty}\frac{n^{\ln\ln n}}{n^3} = \lim_{n\to\infty}n^{\ln\ln n - 3} = \infty
   \end{align*}
   #+END_EXPORT
** $\sqrt{2}^{\ln n}$
   Note that $\ln n$ dominates $\ln\ln n$, and so at large enough $n$, $\sqrt{2}^{\ln n}$ will always be larger.
** $2^{\ln n}$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{2^{\ln n}}{\sqrt{2}^{\ln n}} = \lim_{n\to\infty}\left\lparen\frac{2}{\sqrt{2}}\right\rparen^{\ln n} = \infty
   \end{equation*}
   #+END_EXPORT
** $4^{\ln n}$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\left\lparen\frac{4}{2}\right\rparen^{\ln n} = \infty
   \end{equation*}
   #+END_EXPORT
** $(\ln n)^{\ln n}$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{(\ln n)^{\ln n}}{4^{\ln n}} = \lim_{n\to\infty}\left\lparen\frac{\ln n}{4}\right\rparen^{\ln n} = \infty
   \end{equation*}
   #+END_EXPORT
** $2^{(\ln n)^2}$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{2^{(\ln n)^2}}{(\ln n)^{\ln n}} = \lim_{n\to\infty}\left\lparen\frac{2^{\ln n}}{\ln n}\right\rparen^{\ln n} = \infty
   \end{equation*}
   #+END_EXPORT
** $2^n$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{2^n}{2^{(\ln n)^2}} = \lim_{n\to\infty}2^{n-(\ln n)^2} = \infty
   \end{equation*}
   #+END_EXPORT
   Note that $n\geq (\ln n)^2$ for large enough $n$.
** $n2^n$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty} \frac{n2^n}{2^n} = \lim_{n\to\infty} n = \infty
   \end{equation*}
   #+END_EXPORT
** $e^n$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty} \frac{e^n}{n2^n} = \lim_{n\to\infty}\frac{(e/2)^n}{n} = \infty
   \end{equation*}
   #+END_EXPORT
** $2^2^n$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac\lparen\frac{4}{e}\rparen^n = \infty
   \end{equation*}
   #+END_EXPORT
** 2^{2^{n+1}}
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{2^{2^{n+1}}}{2^{2^n}} = \lim_{n\to\infty}4^{n+1-n} = 4^n = \infty
   \end{equation*}
   #+END_EXPORT
** $n!$
   By common functions corollary (2).
** $(n+1)!$
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \lim_{n\to\infty}\frac{(n+1)!}{n!} = \lim_{n\to\infty} n+1 = \infty
   \end{equation*}
   #+END_EXPORT
* 7
  Three cases:
** $a=1$
   The summation simplifies to: $\sum\limits_{i=1}^n 1^i = n = \Theta(n)$.
** $a<1$
   The asymptotically largest term in the series is $a^1$, which is constant,
   and note that $\lim\limits_{i\to\infty} a^i = 0$, so the asymptotic sum of
   the series is entirely dependent on the value of $a$, which is a constant,
   therefore the entire series has asymptotic growth of $\Theta(1)$.
** $a>1$
   If you add $a^0$ (a constant) to the expression so it becomes a geometric
   series without changing its asymptotic growth rate.
   The sum of a geometric series from $0\to n$ is given by:
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \frac{1-a^{n+1}}{1-a}
   \end{equation*}
   #+END_EXPORT
   Now since we are interested in the asymptotic growth rate, consider only the non-constant terms in this expression so that it becomes:
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \frac{-a^{n+1}}{-a} = a^n
   \end{equation*}
   #+END_EXPORT
   So the summation has a growth rate of $\Theta(a^n)$.
* 8
  #+BEGIN_EXPORT latex
  \begin{proof}
    Base case: $n=1$. \newline
    \begin{equation*}
      \sum_{k=1}^1 k^4 = 1^4 = \frac{1(2)(6\cdot1^3+9\cdot1^2+1-1)}{30} = 1
    \end{equation*}

    Let $n\geq 1$. Assume that for all $j\in[1,n)$,
    $\sum_{k=1}^j k^4=\frac{j(j+1)(6j^3+9j^2+j-1)}{30}$.
    We must show that $\sum_{k=1}^n k^4 = \frac{(n+1)(n+2)(6(n+1)^3+9(n+1)^2+(n+1)-1)}{30}$.

    \begin{align*}
      \sum_{k=1}^{n+1} k^4 &= (n+1)^4 + \sum_{k=1}^n \\
      &= (n+1)^4 + \frac{n(n+1)(6n^3+9n^2+n-1)}{30} &&\tag{by IH j=n}\\
      &= (n^4+4n^3+6n^2+4n+1) + \frac{6n^5+15n^4+10n^3-n}{30} \\
      &= \frac{30n^4+120n^3+180n^2+120n+30 + 6n^5+15n^4+10n^3-n}{30} \\
      &= \frac{6n^5+45n^4+130n^3+180n^2+119n+30}{30} \\
      &= \frac{(n+1)(n+2)(6(n+1)^3 + 9(n+1)^2 + (n+1)-1)}{30} &&\qedhere
    \end{align*}
  \end{proof}
  #+END_EXPORT
