#+OPTIONS: toc:2
* June 25: The Basics
** The numbers
*** $\N=\set{1,2,3,4,5,6,7,8,\ldots}$
*** $\Z=\set{\ldots,-2,-1,0,1,2,\ldots}$
*** $\Z^+=\N\cup\set{0}$
** Arithmatic
*** Assume addition and multiplication works as assumed
** Order
*** $< (\leq)$
** Arithmatic and order work together
*** $a>b \implies a+c > b+c$
*** $a>b \land c>0 \implies ac>bc$
** $\N (\Z^+)$ is well ordered
*** $A\subseteq\N \land A\neq\emptyset \implies \exists a\in A\ s.t.\ \forall b\in A, b\geq a$
*** Equivalent to the principle of mathematical induction
**** Type 1
***** $S\subseteq\N$. If $1\in S \land (n\in S \implies n+1\in S) \implies S=\N$
***** Can start with $a<0$
**** Type 2
***** $1\in S \land (\set{1,\ldots,n}\subseteq S \implies n+1\in S) \implies S=\N$
**** Example
***** For all $n\in\N,\ 2^n\leq\binom{2n}{n}<4^n$ \newline
      Note: $\binom{2n}{n} = \frac{(2n)!}{n!\cdot n!}$
      #+BEGIN_EXPORT latex
      \begin{proof}
        Base case: $n=1$: $\binom{2}{1}=2 \rightarrow 2^1\leq\binom{2}{1}\leq 4^1$ \\
        Inductive case: Suppose that $n\geq 1$ and that $2^n\leq\binom{2n}{n}<4^n$ \\
        Want to show: $2^{n+1}\le\binom{2(n+1)}{n+1}<4^{n+1}$
        \begin{align*}
          \binom{2(n+1)}{n+1} &= \frac{(2n+2)!}{(n+1)!(n+1)!} \\
          &= \frac{(2n+2)(2n+1)}{(n+1)(n+1)}\binom{2n}{n} &&\tag{show binom between 2 and 4} \\
          \frac{(2n+2)(4n+1)}{(n+1)(n+1)} &= 2\cdot\frac{2n+1}{n+1} \\
          2 &< \frac{(2n+2)(4n+1)}{(n+1)(n+1)} < 4
        \end{align*}
        because $1<\frac{2n+1}{n+1}<2$ \\
        Therefore, $2\cdot2^n \leq \binom{2n+2}{n+1} < 4\cdot4^n \qedhere$
      \end{proof}
      #+END_EXPORT
** Divisibility in $\Z$
*** Definition
    $a,b\in\Z$. $a$ divides $b$ if $\exists c\in\Z\ s.t.\ b=a\cdot c$
**** "$a$ divides $b$" $\equiv$ $a|b$
**** If $b=a\cdot c$, write $b/a=c$
*** Properties
**** $1|a\ \forall a\in\Z$
**** $a|a$
**** $a|0$ for all $a\in\Z, a\neq0$
**** $a|b \land a|c \implies a|(bx+cy)\ \forall x,y\in\Z$
     #+BEGIN_EXPORT latex
     \begin{proof}
       By assumption, $b=a\cdot k \land c=a\cdot l (k,l\in\Z)$ \\
       So, $bx+cy=akx + aly = a(kx + ly)$ \\
       and since $kx+ly\in\Z,\ a|(bk+cl)$. $\qedhere$
     \end{proof}
     #+END_EXPORT
**** If $a|b \land b\neq0 \implies |a|\geq|b|$
** The Division Algorithm (Theorm)
*** Definition
    $a,b\in\Z \land b\geq 1 \implies \exists! q,r\in\Z\ s.t.\ a=bq+r \land 0\leq r\leq b-1$ \\
    #+BEGIN_EXPORT latex
    \begin{proof}
      Existance using well-ordering principle. \\
      \begin{align*}
        R &= \setc{a-bq}{q\in\Z} \\
        R^+ &= R\cap\Z^+
      \end{align*}
      Now to show $R^+ \neq\emptyset$:
      Cases: $a\geq0 \implies 0 = 0-b\cdot0\in\R^+$ \\
      $a<0$ choose $q=a-1 \implies a-bq = a-b(a-1) = a+b(1-a) = a-ba+b = a(1-b)+b \geq b$ \\
      because $1-b\leq0$ so $a(1-b)\geq0$ since $a<0$ So $a-b(a-1)\in R^+$ \\
      $\implies R^+\neq\emptyset \implies \R^+$ contains a least element $r_0$. \\
      Let $q_0$ be such that $a-bq_0=r_0\geq0$ \\
      Next need to show $r_0<b$: \\
      Contradiction: Assume $r_0\geq b$
      \begin{align*}
        r_1 = a-bq_0-b &= r_0-b \geq 0 \\
        &= a-b(q_0+1)\in R^+ \\
        r_1 &= r_0 - b < r_0
      \end{align*}
      This contradicts the fact that $r_0$ is the least element in $R^+ \implies$ existance. $\qedhere$
    \end{proof}

    \begin{proof}
      Uniqueness. \\
      Suppose that $a=bq_1+r_1$ with $0\leq r_1\leq b-1$ then:
      \begin{align*}
        bq_1 + r_1 &= bq_0 + r_0 \\
        \text{Without loss of generality, assume: } r_0 &\leq r_1 \\
        \implies 0\leq r_1-r_0 &= bq_0 - bq_1 = b(q_0-q_1) \\
        b\geq1 \implies q_0-q_1 &\geq0 \\
        0 \leq r_0 \leq r_1 &\leq b-1 \\
        \implies 0\leq r_1-r_0 &\leq r_1 \leq b-1 \\
        \implies 0\leq b(q_0-q_1) &\leq b-1 \\
        \implies q_0 - q_1 &= 0 \\
        \implies r_1 - r_0 &= 0 &&\qedhere
      \end{align*}
    \end{proof}
    #+END_EXPORT
** Greatest Common Divisor
*** The GCD of $a,b\in\Z$ is the greatest integer $l$ such that $l|a \land l|b$
*** Facts
**** If $a=b=0 \implies$ no GCD
**** If $a\neq0 \implies$ GCD(a,b)$\leq|a|$
*** If $a\neq0\lor b\neq0 \implies \exists k\in\N\ s.t.\ k|a \land k|b \implies k|d$
    #+BEGIN_EXPORT latex
    \begin{proof}
      Let $D=\setc{ax+by}{x,y\in\Z}$ and $D^+=D\cap\N$. \\
      $D^+\neq\emptyset$ since $a^2+b^2\geq0\in D^+$ \\
      Let $d\in D^+$ be the least element. \\
      Since $d\in D^+\subseteq D,\ \exists x,y\in\Z\ s.t.\ d=ax+by$ \\
      So if $k|a \land k|b \implies k|d$ \\
      Claim: $d|a$ \\
      By division algorithm:
      \begin{align*}
        a &= dq+r &&\tag{$d,q\in\Z,\ 0\leq r<d$} \\
        r &= a-qd \\
        &= a-q(ax+by) \\
        &= a(1-qx) + b(-qy) \\
        \implies r &\in D \\
        r < d \implies r\notin D^+ \land r\geq0 \\
        \implies r &= 0 \\
        \implies d &| a &&\qedhere
      \end{align*}
    \end{proof}
    #+END_EXPORT
*** Lemma about primes
    If $d|a\cdot b \land (d,b)=1 \implies d|a$
*** Questions
**** If $a\neq 0 \lor b\neq0$ does $(a,b)$ exist?
**** If so, how do we find it?
** Exercises
*** Every non-empty set of integers that is bounded above, contains a greatest element
    #+BEGIN_EXPORT latex
    \begin{proof}
      Let $S\subseteq\Z$ be bounded above by $s\in S$. \\
      $s$ must be the greatest integer in $S$ because any $x>s \in S$ would be greater than the bound of $S$ and therefore must not be in $S$. $\qedhere$
    \end{proof}
    #+END_EXPORT
*** Show that if
    $a|b_1, a|b_2, \ldots, a|b_n \implies a|\sum_{i=1}^n x_ib_i\ \forall \set{x_1,\ldots, x_n}\subseteq\Z$
    #+BEGIN_EXPORT latex
    \begin{proof}
      By induction. \\
      Base case: assume $a|b_1 \implies a|x_1b_1\ \forall x_1\in\Z$ by definition. \\
      Inductive hypothesis: assume $a|b_1, \ldots, a|b_n \implies a|\sum_{i=1}^n x_ib_i\ \forall\set{x_1,\ldots,x_n}\subseteq\Z$ \\
      Want to prove: $a|b_1, \ldots, a|b_{n+1} \implies a|\sum_{i=1}^{n+1} x_ib_i\ \forall\set{x_1,\ldots,x_{n+1}}\subseteq\Z$
      \begin{align*}
        a|b_1,\ldots a|b_n &\implies a|\sum_{i=1}^n x_ib_i &&\tag{by inductive hypothesis} \\
        a|b_{n+1} &\implies a|x_{n+1}b_{n+1}\ \forall x_{i+1}\in\Z \\
        a|\sum_{i=1}^n x_ib_i \land a|x_{n+1}b_{n+1} &\implies a|\sum_{i=1}^n x_ib_i + x_{n+1}b_{n+1} \\
        &\implies a|\sum_{i=1}^{n+1} x_ib_i &&\qedhere
      \end{align*}
    \end{proof}
    #+END_EXPORT
*** If $a,b>0 \land a|b \implies b\geq a$
**** Want to prove $a,l\in\N \implies al\geq a$
     #+BEGIN_EXPORT latex
     \begin{proof}
       \begin{align*}
         a|b &\implies \exists k\in\Z\ s.t.\ b=ak \\
         k &= \frac{b}{a} \geq 1 \\
         ak &\geq a \\
         \implies b &\geq a
       \end{align*}
     \end{proof}
     #+END_EXPORT
*** Prove runtime of Euclid's algorithm
* June 27
** Prime numbers
*** $p\in\N$ is a prime if:
**** $p>1$
**** $a|p \implies a=1\lor a=\pm p$
*** Lemmas
**** $p\in\N$ is prime $\iff \forall a,b\in\Z\ p|ab \implies p|a \lor p|b$
     #+BEGIN_EXPORT latex
     \begin{proof}
       $\implies$ \newline
       Assume $a,b>1$. Assume $p$ is prime and $p|ab$. \\
       If $p|a$: done. \\
       If $p\nmid a \implies (a,p)=1$ because if $d|p \land d|a \implies d=1 \lor d=p$ by definition of a prime number. \\
       However, since $p\nmid a \implies d\neq p \implies d=1$ (Corollary 1, pg. 8, $p|ab \land (a,p)=1 \implies p|b$). \\
       \newline
       $\impliedby$ \newline
       Suppose $p>1 \land \forall a,b\in\Z\ p|ab \implies p|a \lor p|b$. \\
       Suppose that $c|p$ \\
       \begin{align*}
         &\implies p|c\cdot d \\
         &p|c \lor p|d \\
         &\implies |p|\geq|c|,|d| \\
         p|c \land |p|\geq|c| &\implies p = |c| \\
         p|d \land |p|\geq|d| &\implies p = |d|
       \end{align*}
     \end{proof}
     #+END_EXPORT
** Unique factorization
*** If $n\in\N \land n>1 \implies$ there is a unique set of primes $p_1,p_2,\ldots,p_k\ s.t.\ n=p_1\cdot p_2\cdot\ldot\cdot p_k$
*** Every $n>1$ is divisible by a prime
    #+BEGIN_EXPORT latex
    \begin{proof}
      Let $S\subseteq\N$ for which the statement fails. \\
      Want to show $S=\emptyset$ \\
      If $S\neq\emptyset \implies S$ contains a least element $n_0$ \\
      Know that $n_0$ is not divisible by a prime, and $\forall n<n_0, n\notin S \implies n=1 \lor n$ is divisible by a prime. \\
      Furthermore $n_0 > 2$. Lastly, $n_0\in S \implies n_0$ is not prime. So $\exists a\in\N, a>1\ s.t.\ a|n_0 \land a<n_0$. \\
      $1<a<n_0 \implies a\notin S \implies \exists p\ s.t.\ p|a$. \\
      $p|a \land a|n_0 \implies p|n_0 \rightarrow\leftarrow \qedhere$
    \end{proof}
    #+END_EXPORT
*** The set of primes is infinite
*** Every $n>1$ is a product of prime factors
*** Euler's theorm (kinda)
    $$\sum_{p\leq N} \frac{1}{p} > \lg(\lgN) - 1$$
**** Corollary: the set of primes is infinite
**** Harmonic series
     $$\log N + 1 > \sum{n=1}^N \frac{1}{n} > \log N$$ \\
     $$\lo N = \int_1^N \frac{1}{x} dx < \sum_{n=1}^N \frac{1}{n}$$
** Excercises
*** If $p$ is prime and $p|(a_1\cdot a_2\cdot\ldot\cdot a_n)$ then $p|a_i$ for some $1\leq i\leq n$
* June 29
** Section 1 HW problem (15b)
   $f(x)=s^2+ax+b=0. a,b\in\Z$ \\
   If $r\in\Q \land f(r)=0 \implies r\in\Z$
   #+BEGIN_EXPORT latex
   \begin{proof}
     Note: $d|ab \land (d,a) \implies d|b$
     \begin{align*}
       r\in\Q &\implies r=n/m \land(n.m)=1 \\
       f(r)=0 &\implies \frac{n^2}{m^2} + a\frac{n}{m}+b=0 \\
       &\implies n^2+anm+bm^2 = 0 \\
       n^2 &= -(anm+bm^2) \\
       &\implies m|n^2 \implies m|n \\
       (m,n)=1 \land m|n &\implies m=\pm1 \\
       &\implies r\in\Z &&\qedhere
     \end{align*}
   \end{proof}
   #+END_EXPORT
*** Proposition
    If $n\in\N$, then $\sqrt{n}\in\Q \iff \sqrt{n}\in\N$ ($n$ is a perfect square)
    #+BEGIN_EXPORT latex
    \begin{proof}
      $\sqrt{n}$ is a solution of $x^2-n=0$. \\
      If $r\in\Q$ and $r^2-n=0 \implies r\in\Z$
    \end{proof}
    #+END_EXPORT
** Diophatine equations
*** Definition
**** Polynomial equation in 1 or more variables with integer coefficients.
**** Want to find rational/integer solutions
** Linear diophantine equations in 2 variables
*** $ax+by=c$ where $a,b,c\in\Z$
*** Integer solutions
**** The equation $ax+by=c$ has no solutions $(x,y)\in\Z^2$ if (a,b)\nmid c$
     Because $(a,b)|(ax+by) \forall x,y\in\Z$
*** If (a,b)|c \implies \exists x,y\in\Z\ s.t.\ ax+by=c$
    #+BEGIN_EXPORT latex
    \begin{proof}
      $\exists x,y\in\Z\ s.t.\ ax+by=d=gcd(a,b)$ \\
      If $d|c \implies c=kd (k\in\Z)$ \\
      Therefore $(ax+by)k=c$ \\
      So $a(xk)+b(yk)=c$. $\qedhere$
    \end{proof}
    #+END_EXPORT
*** If $a,b,c\in\Z \implies ax+by=c$ has solutions $x,y\in\Z \iff gcd(a,b)|c$
*** If $ax_0+by_0=c \implies \forall k\in\Z,\ a(x_0+bk)+b(y_0-ak)=c$
    #+BEGIN_EXPORT latex
    \begin{proof}
      \begin{align*}
        c &= a(x_0+bk) + b(y_0-ak) \\
        &= ax_0+abk + by_0 - abk \\
        &= ax_0+by_0 &&\qedhere
      \end{align*}
    \end{proof}
    #+END_EXPORT
*** The equation $ax+by=c$ has solutions $x,y\in\Z \iff (a,b)|c$
    If $x_0,y_0\in\Z$ is one solution then the set of all solutions is given by
    $\setc{(x,y)}{x=x_0-\frac{b}{gcd(a,b)}\cdot k, y=y_0+\frac{a}{gcd(a,b)}\cdot k \forall k\in\Z}$
    #+BEGIN_EXPORT latex
    \begin{proof}
      If $x_0-k\cdot\frac{b}{gcd(a,b)}, y=y_0+k\cdot\frac{a}{gcd(a,b)}$,
      then $x,y\in\Z$ and $ax+by=\ldots=c$.
    \end{proof}
    #+END_EXPORT
** Sum of two squares
*** For which integers does $a^2+b^2=c$ have a solution?
    Pattern? $n=3+4k \implies n$ is not a sum of two squares
** Excerices
*** Suppose that $n\geq2$, and $f(x)=a_nx^n+a_{n-1}x^{n-1}+\ldots+a_0$
    With $a_i\in\Z$ $0\leq i\leq n$ and $a_n\neq0$
    If there exists a prime $p$ s.t.
**** $p\nmid a_n$
**** $p|a_i$ $\forall i, 0\leq i\leq n$
**** $p^2\nmid a_0$
     then $f(x)=0$ has no verified solutions
*** If $a\equiv b\pmod{m} \land c\equiv d\pmod{m} \implies a\cdot c\equiv b\cdot d\pmod{m}$
