#+OPTIONS: toc:nil

* Excercises
** How mant even primes are there? How many whose last digit is 5?
   1 even prime (2), since any other even number divides by two and therefore can't be a prime. \\
   One number whose last digit is 5 (5), since every other number ending in 5 is divisible by 5.
** Construct a proof of Lemma 2 using induction
   #+BEGIN_EXPORT latex
   \begin{proof}
     Base case: $n=2$. $n$ can be written as a product of primes, $2$. \\
     Inductive hypothesis: $\forall n<k$, $n$ can be written as a product of primes. \\
     Want to show: $k$ can be written as a product of primes. \\
     If $k$ is a prime: done. \\
     Otherwise, by lemma 1, $k$ is divisible by some prime $p_1$ such that $k=p_1n_1$ for some $n_1<k$. \\
     By the inductive hypothesis, $n_1$ can be written as a product of primes, $n_1 = p_2p_3\ldots p_n$. \\
     Therefore, $k=p_1(p_2p_3\ldots p_n)$ which is a product of primes. $\qedhere$
   \end{proof}
   #+END_EXPORT
** Write prime decompositions for 72 and 480
   $72: 2^3\times 3^2$ \\
   $480: 2^5\times 3\times 5$

* Problems

** 1
   Find the prime-power decomposition of 1234, 34560, and 111111
   | 1234 | 2 |
   |  617 | 1 |
   $1234 = 2 * 617$

   | 34560 | 2 |
   | 17280 | 2 |
   |  8640 | 2 |
   |  4320 | 2 |
   |  2160 | 2 |
   |  1080 | 2 |
   |   540 | 2 |
   |   270 | 2 |
   |   135 | 5 |
   |    27 | 3 |
   |     9 | 3 |
   |     3 | 3 |
   $34560 = 2^8 * 3^3 * 5$

   | 111111 |  3 |
   |  37037 |  7 |
   |   5291 | 11 |
   |    481 | 13 |
   |     37 | 37 |
   $111111 = 3*7*11*13*37$
** 3
   $n>2, f(n) = 2^n-1$ is alternating primes and non-primes
   #+BEGIN_EXPORT latex
   \begin{proof}
     $2^n-1 = (2^m)^n - 1 = (2^m-1)(1+2^m+2^{2m}+\ldots+2^{nm})$ \\
     Note that if $(2^m-1)$ is composite, the entire value will be. \\
     For example, 8 and 9 are consecutive composite numbers: $2^8-1 =255$ which is composite, and $2^9-1=511$ which is prime. $\qedhere$
   \end{proof}
   #+END_EXPORT
** 4
*** Show that $6n-1$ and $6n+1$ can be composite $\forall n\geq 1$
    #+BEGIN_EXPORT latex
    \begin{proof}
      Let $n = m+1$
      \begin{align*}
        6(m+1)-1 &= 6m + 5 \\
        6(m+1)+1 &= 6m+7
      \end{align*}
      Want $m$ such that:
      \begin{align*}
        5|6m+5 &\implies 5|6m \implies 5|m \\
        7|6m+5 &\implies 7|6m \implies 7|m
      \end{align*}

      Let $m = 35k \forall k\neq0\ s.t.\ 5|35k \land 7|35k$. \\
      For all these values $6(m+1)\pm1$ will return composite values.
      For example, for $k=1$, $6(35-1)-1=203$, which is composite, and $6(35-1)+1=205$, which is also composite.
    \end{proof}
    #+END_EXPORT
** 7
   Smallest number divisible by 2 and 3 that is both a square and a fith power.
   #+BEGIN_EXPORT latex
   \begin{proof}
     Want a number $n\ s.t.\ 2|n \land 3|n$. Smallest such number is 6. \\
     Also want a number that is both a square and a fifth power. $2*5 = 10$. \\
     $(2*3)^{10} = 6^{10}=60466176$. $\qedhere$
   \end{proof}
   #+END_EXPORT
** 12
   Let $p$ be the least prime factor of $n$, where $n$ is composite.
   Prove that if $p>n^{1/3}$, then $n/p$ is prime.
   #+BEGIN_EXPORT latex
   \begin{proof}
     Given that $p$ is the least prime, $n^{1/3} < p < n^{1/2}$.
     Note that since $p>n^{1/3}$, $(n/p) < n^{2/3}$
     Assume to the contrary that $n/p$ is composite. \\
     $\implies \exists$ least prime $q$ s.t. $q|(n/p)$. \\
     $q|(n/p) \land (n/p)|n \implies q|n$. \\
     Since $p$ is the least prime of $n$, $q>p$.
     $q \leq \sqrt{(n/p)} \implies q\leq n^{1/3}$ \\
     $q \leq n^{1/3} \land q|n \land q>p>n^{1/3}$ \\
     $\rightarrow\leftarrow$ \\
     Therefore $q$ must not exist and $n/p$ must be prime. $\qedhere$
   \end{proof}
   #+END_EXPORT
** 14
