#+TITLE: Homework 1
#+DATE: April 9, 2019
#+OPTIONS: TOC:nil
#+LATEX: \setcounter{secnumdepth}{-1}
* Section 18
** 1
   $12\cdot 16 = 192 \equiv 0 \mod{24}$
** 2
   $16\cdot3 = 48 \equiv 16 \mod{32}$
** 3
   $11\cdot-4 \equiv 11\cdot11 \equiv 121 \equiv 1 \mod{15}$
** 4
   $20\cdot-8 \equiv 20\cdot 18 \equiv 360 \equiv 22 \mod{26}$
** 5
   $(2,3)\cdot(3,5) = (6,15) \equiv (1,6)$
** 6
   $(-3,5)\cdot(2,-4) \equiv (1,5)\cdot(2,7) \equiv (2,35) \equiv (2,2)$
** 14
   $1,-1$
** 15
   $(1,1),(1,-1),(-1,1),(-1,-1)$
** 16
   All non-zero elements ($1,2,3,4$).
** 17
   All non-zero elements.
** 18
   All elements of the form $(1,x,1), (1,x,-1), (-1,x,1)$, or $(-1,x,-1)$ where
   $x\in\Q$ and $x\neq 0$.
** 19
   $1, 3$. since those are the only elements in the ring co-prime to 4.
** 20
*** a
    Note that $\Z/2\Z$ is a ring of order 2, and that each element in
    $M_2(\Z/2\Z)$ is a $2\times2$ matrix, and therefore contains 4 elements
    from $\Z/2\Z$. The question is then reduced to how many different ways
    can we permute 2 elements in 4 positions, which is $2^4 = 16$.
    So the order of the given ring is 16.
*** b
    $\set*{\Matrix{1}{0}{0}{1}, \Matrix{0}{1}{1}{0}, \Matrix{1}{1}{1}{0}, \Matrix{1}{1}{0}{1}, \Matrix{1}{0}{1}{1}, \Matrix{0}{1}{1}{1}}$
** 22
   det is not a ring homomorphism since $\det\left(\Matrix{1}{0}{0}{1} + \Matrix{1}{0}{0}{1}\right) = \det\Matrix{2}{0}{0}{2} = 4 \neq \det\Matrix{1}{0}{0}{1} + \det\Matrix{1}{0}{0}{1} = 1 + 1 = 2$
** 24
** 27
** 36
** 37
   #+BEGIN_EXPORT latex
   \begin{proof}
     Given that $(R,+,\cdot)$ is a ring with unity, and let $U\subseteq R$ be the set of all units in the ring. We want to show that $(U, \cdot)$ is a group. \\
     Firstly, since $\cdot$ is a ring operation, it must be associative.
     Now since $U$ is the set of all unit elements in $R$, every element in $U$
     must have an inverse by construction, and $1\in U$ since $1$ is trivially a unit. \\
     Lastly, to show closure, note that if $a,b\in U$ then $ab\in U$ since $ab$
     has an inverse $b^{-1}a^{-1}$ such that $abb^{-1}a^{-1} = 1$, and so both
     $ab$ and $b^{-1}a^{-1}$ must be units and therefore in $U$, so $(U, \cdot)$ maintains closure. $\qedhere$
   \end{proof}
   #+END_EXPORT
** 38
   Note that $(a+b)(a-b) = a^2 + a(-b) + ba - b^2$.
   This expression is equivalent to $a^2-b^2$ if and only if $ab = ba$ for all elements in the ring. That is, the ring is commutitive.
   So $(a+b)(a-b) = a^2 - b^2$ in a ring $R$ if and only if $R$ is commutitive.
** 44 TODO
   Let $(R, +, \cdot)$ be some commutitive ring.
*** a
    Let $I\subseteq R$ be the set of all idempotent elements in $R$. Now for any $a,b\in I$, $ab\in I$ since $(ab)^2 = (ab)(ab) = a^2b^2 = ab$.
*** b
** 45
** 46
   If elements $a$ and $b$ are nilpotent, then there exists some $m,n\in\Z^+$ such that $a^m=0$ and $b^n=0$.
   Now note that since the ring is commutitive
   #+BEGIN_EXPORT latex
   \begin{equation*}
     (a+b)^{m+n} = \sum_{i=0}^{m+n} \binom{m+n}{i}a^{m+n-i}b^i
   \end{equation*}
   #+END_EXPORT
   By the Binomial Theorem. Now note that for all terms where $i\leq n$:
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \binom{m+n}{i}a^{m+n-i}b^i = \binom{m+n}{i}a^{m}a^{n-i}b^i = \binom{m+n}{i}(0)a^{n-i}b^i = 0
   \end{equation*}
   #+END_EXPORT
   In the case where $n > i$:
   #+BEGIN_EXPORT latex
   \begin{equation*}
     \binom{m+n}{i}a^{m+n-i}b^i = \binom{m+n}{i}a^{m+n-i}b^nb^{i-n} = \binom{m+n}{i}a^{m+n-i}(0)b^{i-n} = 0
   \end{equation*}
   #+END_EXPORT
   Hence, all terms equal 0.
   Therefore, $a+b$ is nilpotent with order at most $m+n$.
** 48
** 49
