#+TITLE: Homework 5
#+DATE: November 8, 2018
#+OPTIONS: TOC:nil
#+LATEX: \setcounter{secnumdepth}{-1}
* Chapter 5
** 5
   Consider the group $((A(S_3)), \circ)$, that is the alternating group in $S_3$.
   $A(S_3)=\set{\Id,(123),(132)}$.
   Now consider $a=(123)\in A(S_3)$ with inverse $b=(132)\in A(S_3)$.
   Consider each possible conjugacy of $b$ in $A(S_3)$:
   #+BEGIN_EXPORT latex
   \begin{align*}
     \Id b\Id^{-1} = \Id b\Id &= b \neq a \\
     aba^{-1} = (ab)b &= b \neq a \\
     bbb^{-1} = b(ba) &= b \neq a
   \end{align*}
   #+END_EXPORT
   Hence $a$ is not conjugate to $b$ in $A(S_3)$ and the statement is proven to be false.

** 6
   A conjugacy class is defined by the relation on $x,y\in G$ such that for some $g\in G$, $x=gyg^{-1}$, which, if $(G,\star)$ is abelian, is equivalent to$x=gg^{-1}y = y$,
   which is the conjugacy class in an abelian group.
** 7
   #+BEGIN_EXPORT latex
   \begin{proof}
     Let $(G,\star)$ be a group. Let $x,y\in G$. To show $x$ is conjugate to $y$
     is to show that there exists some $g\in g$ such that $xy=g(yx)g^{-1}$.
     Now let $g=x$.
     \begin{align*}
       xy &= g(yx)g^{-1} \\
       &= x(yx)x^{-1} \\
       &= (xy)(xx^{-1}) \\
       &= xy
     \end{align*}
     Hence $xy$ is always conjugate to $yx$. $\qedhere$
   \end{proof}
   #+END_EXPORT
** 10
   Firstly, note that for $\sigma\in G$, $\langle \sigma\rangle\subseteq Z_G(\sigma)$,
   since $\sigma$ commutes with itself and all elements in $\langle \sigma\rangle$ are simply products of $\sigma$ with itself.
   Now recall that an element $\tau$ is in the centralizer of $\sigma$ if and only if $\sigma=\tau\sigma\tau^{-1}$, that is all permutations that conjugate $\sigma$ to itself.
   Consider how conjugations affects a permutation in $S_n$: If $\sigma(a)=b$, then under the conjugation, $\sigma(\tau(a))=\tau(b)$, or in cycle-notation, $(a b c) \mapsto (\tau(a)\tau(b)\tau(c))$.
   To consider all such functions that conjugate $\sigma$ to itself, one could consider all possible mappings of $\sigma$ to itself. In cycle-notation, this means considering all possible
   orderings of the same-cycles and translations within those cycles. \\
   For example, consider in $S_4$ the permutation $\sigma=(12)(34)$. This permutation has 8 different allowable combinations
   that each create a unique $\tau\in S_4$ that conjugates $\sigma$ to itself. Those 8 shifts are: $(12)(34),(21)(34),(12)(43),(21)(43),(34)(12)$,
   $(43)(12),(34)(21),(43)(21)$.
   To illustrate, take one of those combinations, such as $(21)(34)$. This permutation is clearly the same as $\sigma$,
   however consider the mapping from $\sigma$ to it $\tau$ such that $\tau(1)=2, \tau(2)=1, \tau(3)=3, \tau(4)=4$ or in cylce notation, $\tau=(12)(3)(4)$. Note that this $\tau$
   conjugates $\sigma$ to itself, since $(\tau(1)\tau(2))(\tau(3)\tau(4)) = (21)(34) = (12)(34)$. \\
   The same applies to every other one of the 8 possible construction. In general, any $\sigma\in S_n$ has $\prod_{l\in\sigma} |l|$ (where $|l|$ is the length of each cycle in $\sigma$) possible
   shifts avaliable to it without changing the order of the cycles. \\
   In considering the additional possible combinations avaliable from changing the order of the cycles,
   we have to remember that we can only map cycles to other cycles of the same length. To consider this, construct an equivalence relation in $\sigma$ where $x,y$ are cycles
   in $\sigma$ taken as sets with the elements as the elements of their cycle. Divide this equivalence class into partitions $K_n=\setc{|x|=n}{\forall x\in\sigma}$.
   That is, a partition $K_n\subseteq\sigma$ has the elements of every cycle of length $n$. Then the number of possible combinations generated by changing the cycle ordering
   is equal to $\prod_{n=1}^\infty |K_n|$, that is, the product of the size of each equivalence class in $\sigma$. This gives us:
   #+BEGIN_EXPORT latex
   \begin{equation}
     |Z_G(\sigma)| = \prod_{n=1}^\infty |K_n|\prod_{l\in\sigma} |l|
   \end{equation}
   #+END_EXPORT
   Calculating the size of $\langle\sigma\rangle$ is much easier, since as has been shown before, the order of $\sigma$ is the least common multiple of all cycle-lengths in $\sigma$.
   Now since $\langle\sigma\rangle\subseteq Z_G(\sigma)$, for them to be equal is only possible when their cardinality is equal.
   It is also important to note that these calculations are dependant only on the cycle-type of the permutation, hence if this is true for one permutation in $S_n$ it is
   true for any other permutation in $S_n$ with the same cycle type. It now only remains to compute this once for every cycle type in $S_3$ and $S_4$:
*** in $G=(S_3,\circ)$
**** $\sigma=\Id$
     $\LCM(1,1,1)=1$ and $(3)\cdot(1)(1)(1) = 3$, so this does not work for $\Id$.
**** $\sigma = (xyz)$
     $|\langle(xyz)\rangle| = LCM(3,1)=3$ and $|Z_G(\sigma)| = \prod_{n=1}^\infty |K_n|\prod_{l\in\sigma} |l| = (1)(3) = 3$.
     So this is true for any element in $S_3$ with cycle type of $3$: $(123), (132)$.
**** $\sigma(xy)(z)$
     $\LCM(2,1)=2$ and $(1)(1)\cdot(2)(1) = 2$. So this is true for any element in $S_3$ with cycle type of $2-1: (12), (13), (23)$.
*** in $G=(S_4, \circ)$
**** $\sigma=\Id$
     $\LCM(1,1,1,1) = 1$ and $(4)\cdot(1)(1)(1)(1) = 4$ so this does not work for $\Id$.
**** $\sigma=(abcd)$
     $\LCM(4,1) = 4$ and $(1)\cdot(4) = 4$ so this is true for any element in $S_4$ with cycle type of 4: $(1234), (1243), (1423), (1324), (1342)$.
**** $\sigma=(abc)(d)$
     $\LCM(3,1)=3$ and $(1)(1)\cdot(3)(1) = 3$ so this is true for any element in $S_4$ with cycle type of $3-1: (12), (13), (14), (23), (24), (34)$.
**** $\sigma=(ab)(cd)$
     $\LCM(2,2)=2$ and $(2)\cdot(2)(2)=8$, so this is not true for any element in $S_4$ with cycle type of $2-2: (12)(34), (13)(24), (14)(23)$.
** 11
   Let $S=Z(G)\subseteq G$.
*** $\Id \in S$
    Trivially, $\Id$ commutes with every element in $G$, and hence is in $S$.
*** Inverses
    If $s\in S$, then for all $g\in G$, $sg=gs$, then $g=s^{-1}gs \implies gs^{-1} = s^{-1}g$ which means that $s^{-1} \in S$.
*** Closure
    Let $x,y \in S$, then for all $g \in G$, $gx=xg$ and $gy=yg$, then:
    #+BEGIN_EXPORT latex
    \begin{align*}
      gx &= xg \\
      ygx &= yxg \\
      g(yx) &= (yx)g
    \end{align*}
    #+END_EXPORT
    hence $yx\in S$.
** 12
   #+BEGIN_EXPORT latex
   \begin{proof}
     Consider the permutation $\sigma\in S_n$ not the identity, then consider the pairwise disjoint permutations $\tau_1\ldots\tau_n=\sigma$.
     Let $a, b, c, d$ be where $a\neq b, c\neq d$ be elements such that $\sigma(a)=b$ and $\sigma(c)=d$. Now consider the transposition $\tau\in S_n$ where $\tau(a)=c$.
     Now consider $\sigma\tau$ where $\sigma(\tau(a))=\sigma(c) = d$, which is not the same as $\tau\sigma$ where $\tau(\sigma(a))=\tau(b)=b$.
     Since $\sigma\tau$ and $\tau\sigma$ do not map $a$ to the same element, they must not be the same permutation and therefore $\sigma$ and $\tau$ must not commute.
     The only case where $\sigma$ can commute with any arbitrary transposition is in the case where $\sigma$ maps every element to itself, that is $\sigma$ is the identity element,
     in which case, $a=b, c=d$ and $\sigma\tau = \sigma(\tau(a))=\sigma(c)=c$ and $\tau\sigma = \tau(\sigma(a))=\tau(a)=c$.
     Therefore, if $S_n$ has at least three elements (since $d$ does not have to be unique), that is $n\geq 3$, $Z(S_n)=\set{\Id}$. $\qedhere$
   \end{proof}
   #+END_EXPORT
** 14
   let $f(g) = gg$, then: $f(xy) = (xy)(xy)$ and $f(x)f(y) = xxyy$. Now $xyxy = xxyy$ is true for every $x,y\in G$ if and only if $x,y \in Z(G)$ and $Z(G)=G$, hence $G$ is an abelian group.
** 16
   #+BEGIN_EXPORT latex
   \begin{proof}
     If $x,y\in(G,\star)$ and $x$ is conjugate to $y$, then there exists some $g\in G$ such that $x=gyg^{-1}$. Let the order of $y$ be $a$ and the order of $x$ be $b$.
     Now consider:
     \begin{align*}
       x^a &= (gyg^{-1})^a \\
       &= (gyg^{-1})(gyg^{-1})\ldots(gyg^{-1}) &&\tag{$a$ times} \\
       &= (g)y(g^{-1}g)(y)(g^{-1}g)(y)\ldots(g^{-1}g)(y)(g^{-1}) \\
       &= gy^ag^{-1} \\
       &= g\star\Id\star g^{-1} \\
       &= \Id
     \end{align*}
     Now if $x^a = \Id$, in which case either $a=0$, then $x=g\Id g^{-1}=\Id$, so $x$ and $y$ have the same order, or $a\geq b$ since if it was less than the
     order of $x$, $x^a$ could not be equal to the identity, but also,
     \begin{align*}
       x^b &= (gyg^{-1})^b \\
       &= (gyg^{-1})(gyg^{-1})\ldots(gyg^{-1}) &&\tag{$b$ times} \\
       &= (g)y(g^{-1}g)(y)(g^{-1}g)(y)\ldots(g^{-1}g)(y)(g^{-1}) \\
       &= gy^bg^{-1} \\
       &= \Id
     \end{align*}
     So if $gy^bg^{-1}=\Id$, then $y^b=\Id$, so either $b=0$, in which case $x=y=\Id$, or $b\geq a$ for the same reason as above, but if $a\geq b$ and $b\geq a$, then $a=b$. $\qedhere$
   \end{proof}
   #+END_EXPORT
