#+TITLE: Homework 6
#+DATE: November 20, 2018
#+OPTIONS: TOC:nil
#+LATEX: \setcounter{secnumdepth}{-1}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{positioning}
* Chapter 5
** 15
*** Every group is isomorphic to itself
    Consider the group identity function $f(x)=x$. This function is
    trivially isomorphic and shows that every group is isomorphic to itself.
*** If $(G,\star)$ and $(H,\star)$ ar groups, and $G\cong H$, then $H\cong G$
    If $G\cong H$, then there exists some isomorphic function $f: G\mapsto H$.
    Now since $f$ is a group ismorphism, its inverse $f^{-1}: H\mapsto G$ exists
    and is also a group isomorphism. Hence, $H\cong G$.
*** If $(J,\star)$ is another group, and $G\cong H$ and $H\cong J$, then $G\cong J$
    Since $G\cong H$, let $f: G\mapsto H$ be a group isomorphism,
    and since $H\cong J$, let $g: H\mapsto H$ be another group isomorphism.
    Now their composition, $g\circ f: G\mapsto J$ is also a group isomorphism
    and therefore $G\cong J$.
** 20
   $Q_8/\mu_2 = \set{\set{1,-1},\set{i,-i},\set{j,-j},\set{k,-k}}$.
   Any isomorphism must map the identity to the identity, so if $f$ is
   an isomorphism from $Q_8/\mu_2 \mapsto \Z/2\Z\times\Z/2\Z$, then $f(1)=(0,0)$.
   Now by inspection there are six possible isomorphisms that maintain this property.
   We know that there are at most 6 isomorphisms because the identity mapping must remain fixed
   so there are three elements left to permute, and $\#S_3 = 3!=6$. Confirming that every one of those is a homomorphism is trivially done by checking each combination
   and so will not be done here.
*** 1
**** $f(1)=(0,0)$
**** $f(i)=(1,0)$
**** $f(j)=(0,1)$
**** $f(k)=(1,1)$
*** 2
**** $f(1)=(0,0)$
**** $f(i)=(0,1)$
**** $f(j)=(1,0)$
**** $f(k)=(1,1)$
*** 3
**** $f(1)=(0,0)$
**** $f(i)=(1,1)$
**** $f(j)=(0,1)$
**** $f(k)=(1,0)$
*** 4
**** $f(1)=(0,0)$
**** $f(i)=(1,1)$
**** $f(j)=(1,0)$
**** $f(k)=(0,1)$
*** 5
**** $f(1)=(0,0)$
**** f(i)=(1,0)$
**** $f(j)=(1,1)$
**** $f(k)=(0,1)$
*** 6
**** $f(1)=(0,0)$
**** $f(i)=(0,1)$
**** $f(j)=(1,1)$
**** $f(k)=(1,0)$
* Chapter 6
** 2
   Consider the connected tree $\Gamma = (V,E)$. For $E'\subset E$ to be a graph,
   it must remain connected while also removing any cycles in $E$. \\
   Consider the potential cycle in $E$: $(n_1,n_2,n_3,\ldots,n_i,n_1)$ with
   $n_2,\ldots,n_i$ pairwise unique. Now since they are unique, that must mean
   that $n_1$ is at least of order two and that both of these edges are able to connect
   to all the same nodes. Hence one of them can be pruned without losing any connections from
   $n_1$ to $n_2,\ldots,n_i$, so connectivity remains while the cycle is removed. This process can
   be repeated until all cycles in $E$ are removed. This subset $E'\subset E$ together with $V$
   forms a connected graph with no cycles, or a tree.
** 3
   By Proposition 6.1, $\sum_{v\in V}\deg(v)=2\cdot \#E$, and since
   $\deg(v)=k$, this is equal to $k\cdot\#V = 2\cdot \#E$. Now since 2 is prime,
   $2|k$ or $2|\#V$, but since $k$ is odd, $2|\#v$, so $\#E = \frac{\#V}{2}k$, so $\#E$ is a multiple of $k$.
** 4
   Consider the tree $\Gamma = (V,E)$, functions $f,g \in \Aut(\Gamma)$ a subgroup of $S_V$,
   and let $x\in E$. We want to show that $f(g(x))\in E$. \\
   Now since $g$ is an automorphism, $g(x)\in E$, and since $g(x)\in E$ and $f$ is an automorphism,
   $f(g(x))\in E$, also, since $f$ and $g$ are bijections, their composition is also a bijection, so $fg\in\Aut(\Gamma)$.
** 7
   1 is trivially in the center of any subgroup.
   For any other element to be in the center, it must commute
   with all elements in that subgroup. Now $\rho$ clearly commutes with
   different powers of itself, so the only element left to check is $s$.
   Now recall that $s\rho=\rho^{-1}s$, and $s\rho^{n/2}=\rho^{-n/2}s=\rho^{n/2}s$,
   which means that $\rho^{n/2}$ commutes with every element if it exists.
   If $n$ is even, then it exists, but if $n$ is odd, $n/2$ is not an integer
   so this permutation does not exist.
   This means that if $n$ is odd, $Z(D_{2n})=\set{\Id}$ and if $n$ is even,
   $Z(D_{2n})=\set{\Id, \rho^{n/2}}$.
** 8
   Question: For which integers $n\geq 3$ is $D_{2n}\subseteq A_n$? \\
   This will be answered by cases of $n\mod{4}$
*** $n\equiv 0 \mod{4}$ or $n\equiv 2\mod{4}$
    If this is true then $n$ is even, so the rotational permutation $\rho\in D_{2n}$
    is therefore an n-cycle permutation, and since $n$ is even, the sign of that permutation is odd, so $\rho\notin A_n$, and $D_{2n}\nsubseteq A_n$.
*** $n\equiv 1\mod{4}$
    Consider the reflection permutation $s\in D_{2n}$. This reflection fixes one element, while permuting every other element in pairs, so it's cycle
    type is a number of 2-cycles combined. The number of cycle 2-cycles is $\frac{n-1}{4}$, and since $n\equiv 1\mod{4}$, $n-1\equiv 0\mod{4}\implies 4|n-1$,
    so there is an even number of 2-cycles, and therefore the sign of the permutation is even. \\
    For the rotation permutation $\rho\in D_{2n}$, it has an order of $n$, so it's also an even cycle, and also the subgroup generated by it will also all be odd permutations.
    Hence $D_{2n}\subseteq A_n$.
*** $n\equiv 3\mod{4}$
    Again consider the reflection permutation $s\in D_{2n}$. This reflection also fixes one element while permuting every other element in pairs, but this time
    $n-1\equiv 2\mod{4}$, so $4\ndiv n-1$, this means that $s$ will have an odd number of 2-cycles, and therefore have an odd sign.
    So $D{2_n}\nsubseteq A_n$ in this case.
** 9
    By definition of $D_{12}$, there exists some element in it, call it $\rho$,
   which has an order of 6. Now for a cycle to have degree 6, the LCM of its cycles
   must be 6. The only possibilities of combinations for an LCM of 6 are a 2-cylce
   and a 3-cycle or a 6-cycle. Now both of these options have an odd sign,
   and therefore can not be in the alternating group $A_4$, so it is impossible
   for $A_4$ to have an element of order 6, and therefore $D_{12}$ can not be
   isomorphic to $A_4$.
** 13
   Found by brute force script. \newline\newline
   #+BEGIN_EXPORT latex
   \begin{tikzpicture}
     [main node/.style={circle,fill=blue!20,draw,minimum size=1cm,inner sep=0pt}]
     \node[main node] (1) {$1$};
     \node[main node] (2) [right = 2.3cm of 1] {$2$};
     \node[main node] (3) [below right = 2.3cm and 1.5cm of 2] {$3$};
     \node[main node] (4) [below left = 2.3cm and 1.5cm of 3] {$4$};
     \node[main node] (5) [left = 2.3cm of 4] {$5$};
     \node[main node] (6) [above left = 2.3cm and 1.5cm of 5] {$6$};

     \path[draw,thick]
     (1) edge node {} (2)
     (2) edge node {} (3)
     (3) edge node {} (4)
     (4) edge node {} (5)
     (3) edge node {} (6)
     (4) edge node {} (6)
     ;
   \end{tikzpicture}
   #+END_EXPORT
