#+TITLE: Homework 5
#+DATE: November 5, 2018
#+OPTIONS: TOC:nil
#+LATEX: \setcounter{secnumdepth}{-1}

* 4.3
  Given that the encryption key is $(320, 155)$, and that $\GCD(320,729)=1$ and $320^{-1}\equiv 344 \mod{729}$,
  the decryption key is $(344, -103)$. The diagraphs that "PSQIUF" forms is $(423, 440, 545)$, which translate to $(338, 354, 24)$,
  which translate to "MONDAY".
* 5.1
  The message "COLLUSION?" becomes the diagraph matrix: $\begin{pmatrix} 2 & 11 & 20 & 8 & 13 \\ 14 & 11 & 18 & 14 & 29\end{pmatrix}$,
  which when encrypted with $A=\Matrix{1}{-1}{3}{-2}, B=\begin{pmatrix}4 \\ 1\end{pmatrix}$, form the matrix: $\begin{pmatrix} -12 & 0 & 2 & -6 & -6 \\ -22 & 11 & 24 & -4 & -19\end{pmatrix}+\begin{pmatrix}4 \\ 1\end{pmatrix} = \begin{pmatrix} 22 & 4 & 6 & 28 & 18 \\ 9 & 12 & 25 & 27 & 11 \end{pmatrix}$
  which form the string "WJEMGZ.,SL". Note: $\Det A = -2 + 3 = 1$, which means that $A^{-1} = \Matrix{-2}{1}{-3}{1}$. So the decryption key is $\left(\Matrix{-2}{1}{-3}{1}, -\Matrix{-8}{1}{-12}{1}\right)$.
* 5.2
  Knowning $B=(0,0)$ and that the message ends with "LES " gives us the following equations:
  #+BEGIN_EXPORT latex
  \begin{align}
    \begin{pmatrix} 24 \\ 17\end{pmatrix} &= A\begin{pmatrix} 11 \\ 4\end{pmatrix} \label{eq1} \\
    \begin{pmatrix}22 \\ 10\end{pmatrix} &= A\begin{pmatrix} 18 \\ 26\end{pmatrix} \label{eq2}
  \end{align}
  #+END_EXPORT
  Now combining $\eqref{eq1}$ with $\eqref{eq2}$, we get:
  #+BEGIN_EXPORT latex
  \begin{equation}
    \begin{pmatrix} 24 & 22 \\ 17 & 10\end{pmatrix} = A\begin{pmatrix} 11 & 18 \\ 4 & 26\end{pmatrix} \label{eq3}
  \end{equation}
  #+END_EXPORT
  with
  #+BEGIN_EXPORT latex
  \begin{align}
    \Det\Matrix{11}{18}{4}{27} = 11\cdot 26 - 18\cdot 4 = 214+30\Z = 4+30\Z \label{eq4}
  \end{align}
  #+END_EXPORT
  Now consider $\eqref{eq3}$ and $\eqref{eq4}$ in $\Z/15$:
  #+BEGIN_EXPORT latex
  \begin{equation*}
    \Matrix{9}{7}{2}{10} = A'\Matrix{11}{3}{4}{11}
  \end{equation*}
  #+END_EXPORT
  with $A'\in\text{Mat}^2(\Z/15\Z)$ by considering $A$ modulo 15.
  Now, $2^{-1}\equiv 8\mod{15}$, so
  #+BEGIN_EXPORT latex
  \begin{equation*}
    \Matrix{11}{3}{4}{11}^{-1} = 8\Matrix{11}{-3}{-4}{11} = \Matrix{14}{3}{14}{14}
  \end{equation*}
  #+END_EXPORT
  which means that
  #+BEGIN_EXPORT latex
  \begin{equation*}
    A' = \Matrix{14}{12}{1}{14}\Matrix{9}{7}{2}{10} = \Matrix{224}{125}{168}{146} = \Matrix{14}{5}{3}{11}
  \end{equation*}
  #+END_EXPORT
  Now there are 16 possibilities for $A = \Matrix{14+15\epsilon_1}{5+15\epsilon_2}{3+15\epsilon_3}{11+15\epsilon_4}$.
** =CASE= $(0,0,0,0)$
   $A = \Matrix{14}{5}{3}{11}, A^{-1} =\Matrix{29}{25}{3}{26}$ and "YRWK"$=$"LES ".
   The first 8 letters of the message are: "U?DIPPWK" = "PERHAPS "
* 5.3
  #+BEGIN_SRC python
    import numpy as np

    values = {chr(i): i-ord('A') for i in range(ord('A'), ord('Z')+1)}
    values[' '] = 26
    values[','] = 27
    values['.'] = 28
    values['?'] = 29
    values_inverse = {v:k for k,v in values.items()}

    def encrypt(A, text):
        if len(text) % 2 == 1:
            text += 'A'
        textN = map(values.get, text)
        textA = [[],[]]
        for n in textN:
            textA[0].append(n)
            textA[1].append(next(textN))
        textM = np.array(textA)
        resultM = A @ textM
        resultA = []
        for n1,n2 in resultM.transpose():
            resultA.append(n1 % 30)
            resultA.append(n2 % 30)
        return "".join(map(values_inverse.get, resultA))
  #+END_SRC

Using the above code the deciphered message is "PERHAPS I COULD BEST DESCRIBE MY EXPERIENCE OF DOING MATHEMATICS IN TERMS OF ENTERING A DARK MANSION. YOU GO INTO THE FIRST ROOM AND IT IS DARK, COMPLETELY DARK. YOU STUMBLE AROUND, BUMPING INTO THE FURNITURE. GRADUALLY, YOU LEARN WHERE EACH PIECE OF FURNITURE IS. AND FINALLY, AFTER SIX MONTHS OR SO, YOU FIND THE LIGHT SWITCH AND TURN IT ON. SUDDENLY, IT IS ALL ILLUMINATED AND YOU CAN SEE EXACTLY WHERE YOU WERE. THEN YOU ENTER THE NEXT DARK ROOM... ANDREW WILES "
* 5.4
** (0,0,0,0)
   $A=\Matrix{9}{1}{13}{4}, \Det A=23. \Inv23\equiv17\mod{30}. \Inv A=\Matrix{8}{13}{19}{3}$. Message is "GIVT ME TWE BTST"
** (0,0,0,1)
   $A=\Matrix{9}{1}{13}{19}, \Det A=158=8$. Done.
** (0,0,1,0)
   $A=\Matrix{9}{1}{28}{4}, \Det A=8$. Done.
** (0,0,1,1)
   $A=\Matrix{9}{1}{28}{19}, \Det A=143=23. \Inv23=17\mod{30}. \Inv A=\Matrix{23}{13}{4}{3}$ Mesage is "GIVT ME EHE BTDE"
** (0,1,0,0)
   $A=\Matrix{9}{16}{13}{4}, \Det A=-182=8$. Done.
** (0,1,0,1)
   $A=\Matrix{9}{16}{13}{19}, \Det A=-37=23. \Inv23=17. \Inv A=\Matrix{23}{28}{19}{3}$. Message is "GIGT ME TWE QTDT"
** (0,1,1,0)
   $A=\Matrix{9}{16}{28}{19}, \Det A=-412=8$. Done.
** (0,1,1,1)
   $A=\Matrix{9}{16}{28}{19}, \Det A=-277=23. \Inv23=17. \Inv A=\Matrix{23}{28}{4}{3}$. Message is "GIGT ME THE QTDE"
** (1,0,0,0)
   $A=\Matrix{24}{1}{13}{4}, \Det A=83=23. \Inv23=17. \Inv A=\Matrix{8}{13}{19}{18}$. Message is "GIVE ME THE BEST". Done.
